Wedding/urls.py
'''from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('',include('adam.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
'''

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings # importing from settings.py
from adam import views
from athul import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about), # '$' means this is the end, nothing after (find expression)
    path('adam/', include('adam.urls')),
    path('athul/', include('athul.urls')), # when this url is requested, look up articles/urls.py
    #path('', adam.home, name='home'), # homepage
    path('', athul.home , name='home')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adam/urls.py
from django.urls import path
from . import views

app_name='adam'

urlpatterns =[
	path('', views.home, name="home"),
	path('login/', views.login, name="login"),
	path('register/', views.register, name="register"),
	path('gallery/', views.gallery, name="gallery")
	]

athul/urls.py
from django.urls import path, re_path
from . import views

app_name = 'athul'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

adam/models.py
from django.db import models
from PIL import Image
from django.utils.timezone import now
# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	date = models.DateTimeField(default=now, editable=False)

	def __str__(self):
		return self.title

class Gallery(models.Model):
	name = models.CharField(max_length=100)
	date = models.DateTimeField(default=now, editable=False)
	image= models.ImageField(null=True, blank=True)
	def __str__(self):
		return self.name

athul/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
	title = models.CharFiels(max_length=100)
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	photo = models.ImageField(default='default.png', blank=True)

	def __str__(self):
		return self.title 

class Gallery(models.Model):
	name = models.CharField(max_length=100)
	date = models.DateTimeField(default=now, editable=False)
	image= models.ImageField(null=True, blank=True)
	def __str__(self):
		return self.name

athul/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'body', 'photo']

Wedding/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

adam/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from .models import Post, Gallery
from django.template import loader
from django.http import HttpResponse
from django.template.loader import get_template 


# Create your views here.

def home(request):
	post = Post.objects.all().order_by('-date')
	context={'post':post}
	template = loader.get_template('adam/home.html')
	return HttpResponse(template.render(context, request))
	#return render(request, 'adam/home.html', context)

def login(request):
	context={}
	
	return render(request, 'adam/login.html',context)

def register(request):
	context={}
	if request.methord =='POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect(request, 'adam/login.html')
	else:
		form = UserCreationForm()
	return render(request, 'adam/register.html', {'form':form})

def gallery(request):
	photos = Gallery.objects.all().order_by('-date')
	context={'photos':photos}
	return render(request, 'adam/gallery.html', context)

athul/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# =======
from .models import Post, Gallery
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Post.objects.all().order_by('date')
    return render(request, 'athul/article_list.html', {'articles':articles})

def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return article_list()
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'formName':form})


def signup_view(request):

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log the user in
            login(request, user)
            return article_list() # in articles/urls.py: app_name and name in urlpatterns
    else:
        form = UserCreationForm()

    return render(request, 'athul/signup.html', {'formName':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

adam/templates/adam/Main.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>AK group</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	
</head>
<body>
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Wedding Site</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      

      
    </ul>
    <div class="form-inline my-2 my-lg-0">
	 <a href="{% url 'login' %}"class="btn btn-warning">Login</a>
	 
  </div>
  <div class="form-inline my-2 my-lg-0">
	 <a href="{% url 'gallery' %}"class="btn btn-warning">Gallery</a></div>
</nav>
	<div class="container">
		{% block content %}
		{% endblock content %}
	</div>
</body>
</html>

adam/templates/adam/gallery.html
{% extends 'adam/Main.html' %}
{% load static %}
{% block content %}
<h1>HEllo</h1>
<iframe width="560" height="315" src="https://www.youtube.com/embed/5zNR3E6WRLE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<div class="row">
	{% for photos in photos %}
	<div class="col-lg-4">
		<div class="article">
			<img src="{{ adam.media.url }}">
			{{ photos.date }}
		</div>
	</div>
	{% endfor %}
</div>


{% endblock content %}

adam/templates/adam/home.html
{% extends 'adam/Main.html' %}
{% load static %}
{% block content %}

<h2>Chat Messages</h2>

<div class="container">
  
  <p>
  {% for post in post %}
    <img src="{% static '/images/test.png' %}" alt="Girl in a jacket" width="50" height="50">
    <div class="container">
      <h4>{{ post.title }}</h4>
      <p>{{ post.body }}</p>
      <p>{{ post.date }}</p>
    </div><br>
  {% endfor %}
</p>
  <span class="time-right">11:00</span>
</div>

<!---
<div class="container darker">
  <img src="{% static '/images/test.png' %}" class="right" style="width:60px;">
  <p>Hey! I'm fine. Thanks for asking!</p>
  <span class="time-left">11:01</span>
</div>

<div class="container">
  <img src="{% static '/images/test.png' %}" alt="Avatar" style="width:60px;">
  <p>Sweet! So, what do you wanna do today?</p>
  <span class="time-right">11:02</span>
</div>

<div class="container darker">
  <img src="{% static '/images/test.png' %}" alt="Avatar" class="right" style="width:100%;">
  <p>Nah, I dunno. Play soccer.. or learn more coding perhaps?</p>
  <span class="time-left">11:05</span>
</div>
--->

{% endblock content %}

adam/templates/adam/login.html
{% extends 'adam/Main.html' %}
{% load static %}
{% block content %}

<form action="/login/" method="POST">
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="{% url 'register' %}">
  <button type="button" class="btn btn-primary">Create Account</button>
</a>
</form>


{% endblock content %}

adam/templates/adam/register.html
{% extends 'adam/Main.html' %}
{% load static %}
{% block content %}
<h1>Sign up</h1>
<form class="site-form" action="index.html" method="POST">
	{{ form }}
	<input type="submit" name="Sign Up">
</form>



{% endblock content %}

athul/templates/athul/article_create.html
{% extends 'layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ formName }}
            <input type="submit"value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

athul/templates/athul/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="article-detail">
        <div class="article">
            <img src="{{ article.thumb.url }}" />
            <h2>{{ article.title }}</h2>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
        </div>
    </div>
{% endblock %}

athul/templates/athul/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <!-- 'articles' is the app_name -->
            <h1>{{ article.title }}</h1>
            <p>{{ article.body }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

athul/templates/athul/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Login</h1>
    <form class="site-form" action="{% url 'athul:login' %}" method="post">
        {% csrf_token %}
        {{ formName }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" value="Login">
    </form>
{% endblock %}

athul/templates/athul/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/athul/signup/" method="post">
        {% csrf_token %}
        {{ formName }}
        <input type="submit" value="Submit">
    </form>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About</title>
    </head>
    <body>
        <h1>About us</h1>
        <p>We like django~ yay~</p>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome to django</p>
    </body>
</html>

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Djangonautic</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>